### ISSUE TITLE
[Joss Review] Automatic dependency installation

### ISSUE THREAD

**Issue by AKuederle** [cadop/seg1d#5]
At the moment all dependencies need to be installed manually, because the package itself is imported in the setup.py file.

The easiest fix would be to remove this import and maintain the package version at two different places. If you want to avoid this, a set of other solutions (e.g. bumpversion) exist.

I would argue that the convenience of installing the package with a single command is very important.

**Comment by cadop** [comment]
What OS are you using?  Could you copy the output when you try to install? It should be installing dependencies with pip (I just tried it again to make sure):

![image](https://user-images.githubusercontent.com/11399119/86828956-dcfab500-c061-11ea-8c17-c2e538f2f6e8.png)

**Comment by AKuederle** [comment]
Ok I just double checked. This only seems to be an issue, if I perform a local install with `pip install .` installing from pypi works as expected.

I could "fix" the local install by removing the self import in the setup.py and because I had issues with these kinds of self imports in the past, I assumed this was related.

OS: Linux

**Comment by cadop** [comment]
The instructions are to use the pypi repository since that doesn't require cloning git and it ensures there is consistent use. The second option could be installing from the release. I wouldn't recommend normal users trying to install by cloning the git repo. Since the first method is the one that is most common/consistent, it is what the documentation shows.  

To resolve the import problem, I directly import the version now 0134881d4d3f8333bd625cc6bfaa98e45216b33c

**Comment by AKuederle** [comment]
That solves the issue thank you :)
